name:                HappyTree
version:             0.2018.1.8
github:              "MarisaKirisame/HappyTree"
license:             BSD3
author:              "Marisa Kirisame"
maintainer:          "lolisa@marisa.moe"
copyright:           "2018 Marisa Kirisame"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Type Safe and End to End Decision Tree 
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/MarisaKirisame/HappyTree#readme>

dependencies:
- base >= 4.7 && < 5
- singletons >= 2.3.1
- generics-sop >= 0.3.1.0
- constraints >= 0.9.1
- safe >= 0.3.15
- criterion >= 1.2.6.0
- Get >= 0.2018.1.10

library:
  source-dirs: src
  ghc-options:
    - -Wno-partial-type-signatures
    - -O

tests:
  HappyTree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HappyTree

executables:
  HappyTreeSample:
    main: Sample.hs
    source-dirs: samples
    dependencies:
    - HappyTree
    ghc-options:
      - -O