name:                HappyTree
version:             0.1.0.0
github:              "MarisaKirisame/HappyTree"
license:             BSD3
author:              "Marisa Kirisame"
maintainer:          "lolisa@marisa.moe"
copyright:           "2018 Marisa Kirisame"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/MarisaKirisame/HappyTree#readme>

dependencies:
- base >= 4.7 && < 5
- singletons == 2.3.1
- generics-sop == 0.3.1.0
- constraints == 0.9.1

library:
  source-dirs: src
  ghc-options:
    - -Wno-partial-type-signatures

executables:
  HappyTree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-partial-type-signatures
    dependencies:
    - HappyTree

tests:
  HappyTree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HappyTree
